app.name=${project.name}
app.version=${project.version}
app.description=${project.description}

app.url.github=https://github.com/B077AS/query-exe
app.url.docs=https://github.com/B077AS/query-exe
app.url.issues=https://github.com/B077AS/query-exe/issues

github.owner=B077AS
github.repo.launcher=query-exe-launcher